services:
    beszel-agent:
        image: henrygd/beszel-agent:latest
        container_name: beszel-agent
        restart: unless-stopped
        network_mode: host
        volumes:
            - ./beszel_agent_data:/var/lib/beszel-agent
            - ./beszel_socket:/beszel_socket
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            LISTEN: /beszel_socket/beszel.sock
            HUB_URL: http://${SERVER_IP}:8090
            TOKEN: ${API_TOKEN}
            KEY: "${API_KEY}"
        # healthcheck:
        #   test: ['CMD', '/agent', 'health']
        #   interval: 120s
