services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: Passw0rd
            PGDATA: /db-data
            POSTGRES_DB: homelabmanager
        volumes:
            - "db-data:/db-data"
            - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: lyam.zambaz@pm.me
            PGADMIN_DEFAULT_PASSWORD: Passw0rd
            POSTGRES_HOST: postgreshost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Passw0rd
            POSTGRES_DB: homelabmanager
            PGADMIN_CONFIG_SERVER_MODE: False
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: False
        ports:
            - 8082:80
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        # command: /bin/sh
        ports:
            - 4398:4398
            - 4399:4399
            - 4397:4397
        volumes:
            - .:/app
            - ../tests:/app/tests
        environment:
            - BYPASS_TTY_INIT_CHECK=true
        depends_on:
            db:
                condition: service_healthy
        # # Allow input
        # tty: true
        # stdin_open: true

volumes:
    db-data:
