FROM python:3.12.13-bookworm

WORKDIR /app

RUN python3 -m venv /venv

RUN apt-get update && apt-get install -y rclone curl # py-spy

COPY requirements.txt requirements.txt

RUN . /venv/bin/activate && pip install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]
