services:
    reverse-proxy:
        build: .
        environment:
            API_URL: your-api-url
            API_KEY: your-api-key
            CLIENT_MAX_BODY_SIZE: 20G # Adjust this in config
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./logs:/usr/local/openresty/nginx/logs/
        ports:
            - 80:80
            - 443:443
