
server {
        listen 80 default_server;
        server_name _;
	client_max_body_size 20G;
        location /wakapi/ {
            proxy_pass http://192.168.1.154:3039/api/;
        }

        location / {
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_pass http://192.168.1.154:9000/;
        }

        location /onlyoffice/ {
            proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header X-Forwarded-Host $http_host/onlyoffice;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://192.168.1.39:9980/;
        }

        location /siteapi/ {
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_pass http://192.168.1.154:8000/;
        }

        location /nextcloud/ {
            proxy_pass http://192.168.1.39:8081/;
        }

        location /change/ {
            auth_basic "changedetection.io private instance";
            auth_basic_user_file /app/.htpasswd;
            proxy_set_header Host localhost;
            proxy_set_header X-Forwarded-Prefix /change;
            proxy_set_header X-Forwarded-Proto /http;
            proxy_pass http://192.168.1.154:5002/;
        }

        location /obsidian-livesync/ {
            proxy_pass http://192.168.1.154:5984/;
        }
    }

    server {
        #server_name webdash.dev; # managed by Certbot
        server_name _;
	client_max_body_size 20G;
        
        location /wakapi/ {
            proxy_pass http://192.168.1.154:3039/api/;
        }

        location / {
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_pass http://192.168.1.154:9000/;
        }

        location /onlyoffice/ {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header X-Forwarded-Host $http_host/onlyoffice;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://192.168.1.39:9980/;
        }

        location /siteapi/ {
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_pass http://192.168.1.154:8000/;
        }

        location /nextcloud/ {
            proxy_pass http://192.168.1.39:8081/;
        }

        location /change/ {
            auth_basic "changedetection.io private instance";
            auth_basic_user_file /app/.htpasswd;
            proxy_set_header Host localhost;
            proxy_set_header X-Forwarded-Prefix /change;
            proxy_set_header X-Forwarded-Proto /http;
            proxy_pass http://192.168.1.154:5002/;
        }

        location /obsidian-livesync/ {
            proxy_pass http://192.168.1.154:5984/;
        }
    

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/webdash.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/webdash.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    }
    server {
    if ($host = webdash.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80 ;
    server_name webdash.dev;
    return 404; # managed by Certbot
    }
