CREATE TABLE server (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    id_str VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    ip VARCHAR(15) NOT NULL UNIQUE,
    api_key VARCHAR(36) UNIQUE,
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    reverse_api_key VARCHAR(36) NOT NULL UNIQUE
);
