[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-rustls = "0.26.5"
tokio = { version = "1.53.1", features = ["full"] }
thiserror = "2.0.20"
ini = "2.0.0"
serde_json = "1.0.151"
serde = { version = "1.0.188", features = ["derive"] }
log = "0.4.34"
simple_logger = { version = "5.2.0", features = ["colors", "timestamps", "stderr"] }
which = "8.0.6"
