CREATE TABLE backup_config (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL REFERENCES service(id) ON DELETE CASCADE,
    id_str VARCHAR(100) NOT NULL UNIQUE,
    last TIMESTAMP,
    disabled BOOLEAN NOT NULL DEFAULT FALSE
);
